language: python
services:
  - docker
python:
  - '3.6'
cache:
  directories:
  - node_modules
env:
  - DEV_MNGR_CRYPTO_PASS="KamehameHA"
  - DEV_MNGR_CRYPTO_IV=1234567890123456
  - DEV_MNGR_CRYPTO_SALT="shuriken"
before_install:
  - npm install aglio
script:
  - 'docker build -t dojot/device-manager .'
  - 'docker build -t dredd/test -f tests/Dockerfile .'
  - 'docker-compose -p test -f tests/docker-compose.yaml up -d kafka data-broker postgres device-manager device-manager-redis'
  - 'docker-compose -p test -f tests/docker-compose.yaml run --rm test-runner'
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
